<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/profile.proto

namespace Zwp\Monitor\Vox;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>vox.Items</code>
 */
class Items extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string app = 1;</code>
     */
    private $app = '';
    /**
     * <code>string hostname = 2;</code>
     */
    private $hostname = '';
    /**
     * <code>repeated .vox.Item items = 3;</code>
     */
    private $items;

    public function __construct() {
        parent::__construct();
    }

    /**
     * <code>string app = 1;</code>
     */
    public function getApp()
    {
        return $this->app;
    }

    /**
     * <code>string app = 1;</code>
     */
    public function setApp($var)
    {
        GPBUtil::checkString($var, True);
        $this->app = $var;
    }

    /**
     * <code>string hostname = 2;</code>
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * <code>string hostname = 2;</code>
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;
    }

    /**
     * <code>repeated .vox.Item items = 3;</code>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * <code>repeated .vox.Item items = 3;</code>
     */
    public function setItems(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, Item::class);
        $this->items = $arr;
    }

}

