<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/profile.proto

namespace Zwp\Monitor\Vox;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>vox.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *in seconds
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    private $timestamp = 0;
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <code>string type = 3;</code>
     */
    private $type = '';
    /**
     * <code>int64 value = 4;</code>
     */
    private $value = 0;
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    private $tags;
    /**
     * <code>map&lt;string, double&gt; fields = 6;</code>
     */
    private $fields;
    /**
     * <code>int64 duration = 7;</code>
     */
    private $duration = 0;
    /**
     * <code>int64 min = 8;</code>
     */
    private $min = 0;
    /**
     * <code>int64 max = 9;</code>
     */
    private $max = 0;

    public function __construct() {
        \GPBMetadata\Proto\Profile::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *in seconds
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * <pre>
     *in seconds
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>string type = 3;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>string type = 3;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;
    }

    /**
     * <code>int64 value = 4;</code>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * <code>int64 value = 4;</code>
     */
    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;
    }

    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    public function setTags(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;
    }

    /**
     * <code>map&lt;string, double&gt; fields = 6;</code>
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * <code>map&lt;string, double&gt; fields = 6;</code>
     */
    public function setFields(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->fields = $arr;
    }

    /**
     * <code>int64 duration = 7;</code>
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * <code>int64 duration = 7;</code>
     */
    public function setDuration($var)
    {
        GPBUtil::checkInt64($var);
        $this->duration = $var;
    }

    /**
     * <code>int64 min = 8;</code>
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * <code>int64 min = 8;</code>
     */
    public function setMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->min = $var;
    }

    /**
     * <code>int64 max = 9;</code>
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * <code>int64 max = 9;</code>
     */
    public function setMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->max = $var;
    }

}

